# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7672cda7875aa5f41245163f13dfe887"
name = "test-diamond-search"
handle = "test-diamond-search"
application_url = "https://ace-allegedly-louse.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-test-diamond.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_publications,write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://ace-allegedly-louse.ngrok-free.app/auth/callback",
  "https://ace-allegedly-louse.ngrok-free.app/auth/shopify/callback",
  "https://ace-allegedly-louse.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://ace-allegedly-louse.ngrok-free.app/diamond-search"
subpath = "diamond-search"
prefix = "apps"

[pos]
embedded = false
